In [ ]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])
b=np.array([1,2,3])
assert(a.dtype == np.int64)

print(b.shape)
print(a.shape)

assert (b.shape == (3,))    # returns a tuple so it has to be (3,)
assert(a.shape == (2,3))   # returns a tuple
assert(isinstance(a.shape , tuple))     # is instance check the datatype



(3,)
(2, 3)


In [12]:
c = [1,2,3]
b == c

array([ True,  True,  True])

In [15]:
assert np.array_equal(b,c)
assert np.array_equal(b,[1,2,3])

In [16]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(a.ndim)
print(a.shape)
print(a.size)


2
(3, 3)
9


In [43]:
a=np.random.rand(2,3,3)
b=np.random.randint(0,4,4)
c=np.random.random(6)
print(a.ndim)
print(a.shape)
print (a)
print (b)
print(c)

3
(2, 3, 3)
[[[0.79813632 0.08369006 0.4117892 ]
  [0.44656029 0.98973734 0.69100961]
  [0.44566557 0.56932678 0.96534375]]

 [[0.52543218 0.68509843 0.77752974]
  [0.65955471 0.36776981 0.80572601]
  [0.20962341 0.16305204 0.17098383]]]
[0 0 0 3]
[0.98754444 0.34962466 0.27215534 0.34031319 0.88360956 0.14432323]


In [26]:
a=np.array(np.arange(1,25))
b=a.reshape(2,12)

print(a)
print(b)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


### neural network using N p array


In [28]:
inputs=np.random.rand(10)
print(inputs)

[0.21249911 0.45907407 0.6506071  0.59712192 0.72215663 0.36472246
 0.86751075 0.26089529 0.5877914  0.55526549]


In [ ]:
weights1 = np.random.rand(10)
print(weights1)

[0.91042349 0.54445416 0.24294575 0.69508934 0.98336653 0.96300591
 0.40049327 0.83032322 0.60540098 0.07358132]


In [ ]:
bias1 = np.random.randint(0,10)
print(bias1)

2


In [ ]:
h1 = np.dot(inputs,weights1)+bias1
print(h1)

5.038665090989502


In [45]:
weights2 = np.random.rand(10)
print(weights2)

[0.06512803 0.32016949 0.16113986 0.07861074 0.90730064 0.17829556
 0.53420439 0.54697934 0.36982638 0.17477303]


In [46]:
bias2 = np.random.randint(0,10)
print(bias2)

7


In [47]:
h2 = np.dot(inputs,weights2)+bias2
print(h2)

8.953400234325537


In [51]:
weights3 = np.random.rand(10)
print(weights3)

weights4 = np.random.rand(10)
print(weights4)

[0.74277501 0.86722623 0.21532294 0.48182117 0.52217976 0.19133403
 0.68968955 0.3331673  0.19439457 0.14349059]
[0.57471505 0.19335031 0.45434996 0.93782334 0.89784104 0.45389455
 0.26070676 0.19876491 0.32811002 0.70032389]


In [53]:
bias3 = np.random.randint(0,10)
print(bias3)
bias4 = np.random.randint(0,10)
print(bias4)

0
1


In [55]:
result = []

output1 = np.dot(h1,weights3)+ bias3
output2 = np.dot(h2,weights4)+ bias4

result.append(output1)
result.append(output2)

print(result)

[array([3.74259452, 4.36966253, 1.08494017, 2.4277355 , 2.63108893,
       0.96406811, 3.47511468, 1.67871845, 0.97948912, 0.72300105]), array([6.1456539 , 2.73114273, 5.06797702, 9.39670769, 9.03873018,
       5.06389958, 3.33421197, 2.77962177, 3.93770033, 7.27028006])]
